import type { FC } from 'react';
import MetricCard from './MetricCard';
import ConfidenceMeter from './ConfidenceMeter';

interface OverviewSectionProps {
  aiSummary?: {
    paragraphs: string[];
    updated_at?: string;
    generated?: boolean;
    mode?: 'historical-only' | 'mixed' | 'forecast';
    advisory?: boolean;
    explainability_available?: boolean;
  } | null;
  financials?: {
    margins?: {
      operating?: number | null;
      net?: number | null;
    } | null;
    ratios?: {
      name: string;
      value: number | string | null;
    }[];
  } | null;
  shareholdingPresent: boolean;
  marketPresent: boolean;
  onToggleSummary: () => void;
  summaryExpanded: boolean;
  onExplainability: () => void;
}

const formatPercentage = (value: number | null | undefined) => {
  if (value === null || value === undefined || Number.isNaN(value)) {
    return '—';
  }
  return `${value.toFixed(2)}%`;
};

const formatRatioValue = (value: number | string | null | undefined) => {
  if (value === null || value === undefined || value === '') return '—';
  if (typeof value === 'number') return value.toFixed(2);
  return value;
};

const OverviewSection: FC<OverviewSectionProps> = ({
  aiSummary,
  financials,
  shareholdingPresent,
  marketPresent,
  onToggleSummary,
  summaryExpanded,
  onExplainability,
}) => {
  const ratios = Array.isArray(financials?.ratios) ? financials?.ratios : [];
  const roe = ratios.find((ratio) => typeof ratio.name === 'string' && ratio.name.toLowerCase().includes('roe'));
  const interestCoverage = ratios.find(
    (ratio) => typeof ratio.name === 'string' && ratio.name.toLowerCase().includes('interest coverage'),
  );

  const financialsPresent = Boolean(
    (financials?.margins?.operating !== undefined && financials?.margins?.operating !== null) ||
      (financials?.margins?.net !== undefined && financials?.margins?.net !== null) ||
      (roe && roe.value !== null && roe.value !== undefined),
  );

  return (
    <div className="space-y-6">
      <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">
        <MetricCard label="Operating margin" value={formatPercentage(financials?.margins?.operating ?? null)} helper="Reported margin for the latest disclosed period." />
        <MetricCard label="Net margin" value={formatPercentage(financials?.margins?.net ?? null)} helper="Net profit divided by revenue for the stated period." />
        <MetricCard
          label="Return on equity"
          value={formatRatioValue(roe?.value)}
          helper="Based on historical filings. Expressed as stated in company disclosures."
        />
        <MetricCard
          label="Interest coverage"
          value={formatRatioValue(interestCoverage?.value)}
          helper="Reported coverage ratio from the latest available filings."
        />
      </div>

      <ConfidenceMeter financialsPresent={financialsPresent} shareholdingPresent={shareholdingPresent} marketPresent={marketPresent} />

      <div className="bg-white border border-neutral-200 rounded-xl p-6 shadow-subtle">
        <div className="bg-neutral-100 border border-neutral-200 rounded-lg px-4 py-3 text-xs text-neutral-600">
          <p className="font-medium text-neutral-700">AI-generated historical summary</p>
          <p className="mt-1 text-neutral-500">
            This summary is generated by analyzing historical financial statements and disclosures. It does not constitute investment advice or forward-looking guidance.
          </p>
        </div>
        <button
          type="button"
          onClick={onToggleSummary}
          className="mt-4 flex w-full items-center justify-between rounded-lg border border-neutral-200 px-4 py-2 text-sm font-semibold text-neutral-800 hover:border-neutral-300 focus:outline-none focus-visible:ring-2 focus-visible:ring-neutral-900/10"
          aria-expanded={summaryExpanded}
          aria-controls="overview-ai-summary"
          disabled={!aiSummary?.paragraphs?.length}
        >
          <span>{aiSummary?.paragraphs?.length ? 'View analytical summary' : 'Summary will appear once filings are processed'}</span>
          <svg
            className={`h-4 w-4 text-neutral-500 transition-transform ${summaryExpanded ? 'rotate-90' : ''}`}
            viewBox="0 0 20 20"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M6 4L14 10L6 16" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
        {summaryExpanded && aiSummary?.paragraphs?.length ? (
          <div id="overview-ai-summary" className="mt-4 space-y-3 text-sm text-neutral-600">
            {aiSummary.paragraphs.map((paragraph, index) => (
              <p key={index} className="leading-relaxed">
                {paragraph}
              </p>
            ))}
            <dl className="text-xs text-neutral-400 space-y-1">
              <div className="flex justify-between">
                <dt>Updated</dt>
                <dd>{aiSummary.updated_at ?? 'Not available'}</dd>
              </div>
              <div className="flex justify-between">
                <dt>Mode</dt>
                <dd>{aiSummary.mode ?? 'historical-only'}</dd>
              </div>
              <div className="flex justify-between">
                <dt>Advisory</dt>
                <dd>{aiSummary.advisory ? 'Contains advisory language' : 'Historical descriptive only'}</dd>
              </div>
              <div className="flex justify-between">
                <dt>Explainability</dt>
                <dd>{aiSummary.explainability_available ? 'Available' : 'Not available'}</dd>
              </div>
            </dl>
          </div>
        ) : null}

        <button
          type="button"
          onClick={onExplainability}
          className="mt-4 text-xs text-neutral-500 underline-offset-4 hover:text-neutral-800 hover:underline focus:outline-none focus-visible:ring-2 focus-visible:ring-neutral-900/10"
        >
          How Fundametrics prepares these summaries
        </button>
      </div>
    </div>
  );
};

export default OverviewSection;
